server:
  port: 8002
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: aishu123
    url: jdbc:postgresql://postgres:5432/gasgodb
    username: aishu
  jpa:
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    hibernate:
      ddl-auto: update
    show-sql: true